[package]
name = "sepiascraped"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
bevy_egui = "0.25"
bevy-inspector-egui = { git = "https://github.com/Aztro-dev/bevy-inspector-egui" }
petgraph = "0.6.4"
bevy_mod_picking = { git = "https://github.com/StrikeForceZero/bevy_mod_picking", branch = "bevy-0.13", default-features = false, features = [
    "backend_raycast",
    "backend_bevy_ui",
    "backend_sprite",
#    "debug",
    "selection",
#    "highlight",
    "backend_egui" ] }
bevy_prototype_lyon = "0.11"
layout-rs = "0.1"
log = "0.4.20"
steel-core = { git="https://github.com/mattwparas/steel.git", branch = "master" }
steel-derive= { git="https://github.com/mattwparas/steel.git", branch = "master" }
