[package]
name = "sepiascraped"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
bevy_egui = "0.25"
petgraph = "0.6.4"
bevy_mod_picking = { git = "https://github.com/StrikeForceZero/bevy_mod_picking", branch = "bevy-0.13", default-features = false, features = [
    "backend_raycast",
    "backend_bevy_ui",
    "backend_sprite",
#    "debug",
    "selection",
#    "highlight",
    "backend_egui" ] }
bevy_prototype_lyon = "0.11"
layout-rs = "0.1"
log = "0.4.20"
boa_engine = { git = "https://github.com/boa-dev/boa" }
boa_gc = { git = "https://github.com/boa-dev/boa" }
boa_runtime = { git = "https://github.com/boa-dev/boa" }
bevy_mod_debugdump = "0.10"