[package]
name = "sepiascraped"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
bevy_egui = { git = "https://github.com/eerii/bevy_egui" }
egui_graph = { path = "../../mitchmindtree/egui_graph" }
petgraph = "0.6.4"
